activity.get:
    path: /admin/activity/{page<\d+>?1}
    controller: App\Controller\ActivityController::getActivity
activity.put:
    path: /{r}
    controller: App\Controller\ActivityController::putActivity
    requirements:
      r: ".*"
